package mattonfire.dnd.dungeon;

import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import mattonfire.dnd.classes.DnDClasses;
import mattonfire.dnd.world.gen.dungeon.DungeonTheme;
import net.fabricmc.fabric.api.entity.event.v1.ServerLivingEntityEvents;
import net.minecraft.entity.LivingEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.ItemStack;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.context.LootContext;
import net.minecraft.loot.context.LootContextParameters;
import net.minecraft.loot.context.LootContextTypes;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.math.Vec3d;
import net.minecraft.world.GameRules;
import org.jetbrains.annotations.Nullable;

/**
 * Dungeon loot (see {@code docs/systems/dungeon-loot.md}). Table names carry the theme, the room
 * and the Challenge tier, so a chest needs nothing but its loot table id:
 * <ul>
 * <li>{@code dndclasses:chests/dungeon/<theme>_<room>_t<tier>}: room chests ({@code encounter},
 * {@code secret}, {@code side_vault}); locked, with the tier's lock DC ({@link #lockDc})</li>
 * <li>{@code dndclasses:chests/dungeon/vault_t<tier>} and {@code vault_salvage}: the Hoard Coffer</li>
 * <li>{@code dndclasses:gameplay/dungeon_elite_t<tier>}: one extra roll from each Veteran a player kills</li>
 * </ul>
 * The tables are generated by {@code tools/dungeon_loot.py}.
 */
public final class DungeonLoot {
    public static final String CHEST_PREFIX = "chests/dungeon/";
    /** Lock DC by tier (design 2.2), and the extra for a class-gated side vault. */
    private static final int[] TIER_DC = {12, 13, 15, 17};
    public static final int SIDE_VAULT_DC_BONUS = 2;
    private static final Pattern TIER_SUFFIX = Pattern.compile("_t([1-4])$");

    private DungeonLoot() {
    }

    public static void register() {
        DungeonTierLootCondition.register();
        DungeonRegistry.register();
        ServerLivingEntityEvents.AFTER_DEATH.register((entity, source) -> {
            if (entity.world instanceof ServerWorld world && entity.getCommandTags().contains(EncounterBuilder.ELITE_TAG)
                    && entity.getCommandTags().contains(EncounterBuilder.TAG)) {
                PlayerEntity killer = source.getAttacker() instanceof PlayerEntity p ? p
                        : entity.getPrimeAdversary() instanceof PlayerEntity p ? p : null;
                if (killer != null) {
                    dropEliteLoot(world, entity, killer);
                }
            }
        });
    }

    /** The theme's word in loot table names: crypt, warren, ruin. */
    public static String prefix(DungeonTheme theme) {
        return switch (theme) {
            case GOBLIN_WARREN -> "warren";
            case DWARVEN_RUIN -> "ruin";
            default -> theme.id().toLowerCase(Locale.ROOT);
        };
    }

    /** A room chest's table: {@code dndclasses:chests/dungeon/<theme>_<room>_t<tier>}. */
    public static Identifier chestTable(DungeonTheme theme, String room, int tier) {
        return new Identifier(DnDClasses.MOD_ID, CHEST_PREFIX + prefix(theme) + "_" + room + "_t" + MathHelper.clamp(tier, 1, 4));
    }

    public static Identifier vaultTable(int tier) {
        return new Identifier(DnDClasses.MOD_ID, CHEST_PREFIX + "vault_t" + MathHelper.clamp(tier, 1, 4));
    }

    public static Identifier salvageTable() {
        return new Identifier(DnDClasses.MOD_ID, CHEST_PREFIX + "vault_salvage");
    }

    public static Identifier eliteTable(int tier) {
        return new Identifier(DnDClasses.MOD_ID, "gameplay/dungeon_elite_t" + MathHelper.clamp(tier, 1, 4));
    }

    public static int tierDc(int tier) {
        return TIER_DC[MathHelper.clamp(tier, 1, 4) - 1];
    }

    /**
     * The lock DC of a dungeon chest table ({@code dndclasses:chests/dungeon/..._t<tier>}): 12/13/15/17
     * by tier, +2 for a side vault. Null for any other table.
     */
    @Nullable
    public static Integer lockDc(Identifier table) {
        if (!table.getNamespace().equals(DnDClasses.MOD_ID) || !table.getPath().startsWith(CHEST_PREFIX)) {
            return null;
        }
        Matcher m = TIER_SUFFIX.matcher(table.getPath());
        int dc = tierDc(m.find() ? Integer.parseInt(m.group(1)) : 1);
        return table.getPath().contains("side_vault") ? dc + SIDE_VAULT_DC_BONUS : dc;
    }

    /** Rolls a chest-type table at {@code origin} for {@code player} (luck counts). */
    public static List<ItemStack> roll(ServerWorld world, Identifier table, Vec3d origin, @Nullable PlayerEntity player) {
        LootTable loot = world.getServer().getLootManager().getTable(table);
        LootContext.Builder builder = new LootContext.Builder(world).parameter(LootContextParameters.ORIGIN, origin)
                .random(world.random);
        if (player != null) {
            builder.luck(player.getLuck()).parameter(LootContextParameters.THIS_ENTITY, player);
        }
        return loot.generateLoot(builder.build(LootContextTypes.CHEST));
    }

    /** A Veteran's extra roll from {@code gameplay/dungeon_elite_t<tier>}, dropped where it died. */
    private static void dropEliteLoot(ServerWorld world, LivingEntity entity, PlayerEntity killer) {
        if (!world.getGameRules().getBoolean(GameRules.DO_MOB_LOOT)) {
            return;
        }
        long[] room = EncounterBuilder.roomOf(entity);
        DungeonState dungeon = room == null ? null : DungeonRegistry.get(world).get(room[0]);
        int tier = dungeon != null ? dungeon.tier()
                : DungeonRegistry.get(world).containing(BlockPos.ofFloored(entity.getPos())).map(DungeonState::tier).orElse(1);
        List<ItemStack> drops = roll(world, eliteTable(tier), entity.getPos(), killer);
        for (ItemStack stack : drops) {
            entity.dropStack(stack);
        }
        DnDClasses.LOGGER.info("[DungeonLoot] Veteran {} dropped {} extra stack(s) from {}", entity.getType().getUntranslatedName(),
                drops.size(), eliteTable(tier));
    }
}
